name: Build and Run

on: [push]

jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Build
        run: |
          cmake -B build -D CMAKE_CUDA_ARCHITECTURES=86
          cd build
          make -j
      - name: Test CPU
        run: cd build && ./src/main-cpu
      - name: Test GPU
        run: cd build && ./src/main-gpu
