name: Build and Run

on: [push]

jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      # - name: Install CMake
      #   run: sudo apt-get install cmake
      - name: Build
        run: |
          cmake -B build
          cd build
          make -j
      - name: Test
        run: ./build/src/main-cpu
